### ISSUE TITLE
Link to repo broken

### ISSUE THREAD

**Issue by angeek** [veekaybee/what_are_embeddings#28]
Hi,

Thanks for the paper, it's a really nice lecture.

This [link ](https://github.com/veekaybee/what_are_embeddings/blob/main/embeddings.tex#L1760C35-L1760C35)is broken (http 404) 
I've searching that implementation in the viberary repo and I think it might be this notebook?

https://github.com/veekaybee/viberary/blob/main/src/notebooks/04_word2vec.ipynb

**Comment by veekaybee** [comment]
Thanks for raising this issue! The underlying issue was two things: 

1. Wrong link
2. The correct link notebook didn't render correctly because of escape quotes, fixed here: https://github.com/veekaybee/viberary/commit/5752368c64ce9c4c7c48d3d4e0863fec7706dc76

I've changed the link: https://github.com/veekaybee/what_are_embeddings/commit/8680d421751db0493bc0a7907f37931ac45686f2
